### ISSUE TITLE
Biomes O' Plenty Biomes Not Generating

### ISSUE THREAD

**Issue by MysticcWaters** [djsimmonds/tectonic-bop#1]
Hi, we were talking in Apollo's Discord. The mod "loads" just fine, but I can't get the actual BoP biomes to generate.

I tested this out with:
Biomes O' Plenty
Tectonic
Tectonic for Biomes O' Plenty
Terrablender

I changed the Biomes O' Plenty config so that the weights were zero as well, but no luck. Any steps that I'm missing?

[latest.log](https://github.com/djsimmonds/tectonic-bop/files/11195263/latest.log)

**Comment by djsimmonds** [comment]
the log looks incomplete. is that really all there is? i don't even see anything about tectonic or tectonicbop in the file. what versions are all the mods? can you also share the tectonicbopconfig.toml file in the configs folder?

**Comment by djsimmonds** [comment]
also, take a picture of your datapack load order for the world you created

**Comment by MysticcWaters** [comment]
Hey, sorry about that. I somehow sent an earlier log file from when I had just started up that Minecraft instance. Here is an updated log with a new world that I created (issue still occurs):

[latest.log](https://github.com/djsimmonds/tectonic-bop/files/11195602/latest.log)

Also, here is the load order:

![Datapack Load Order](https://user-images.githubusercontent.com/130418925/231037521-a04be7ee-7dd8-498d-bb83-4c4249203df2.png)

And, the versions of the mods are:
Biomes O' Plenty - 17.1.2.544
Tectonic - 1.1.9b
Tectonic for Biomes O' Plenty - 1.1.9b
Terrablender - 2.0.1.136

**Comment by djsimmonds** [comment]
ok, i have done a bit of testing and noted the following:
1) whether terrablender configs are default or set to zero, or whether bop terrablender configs are default or set to zero, BOP biomes generated for me in every case
2) what i noticed (and did not expect), was that if terrablender configs were set to zero (whether or not bop terrablender configs were set to zero), this impacted generation of certain tectonic biomes (in particularly, no underground rivers were generating); keeping terrablender configs default (whether or not terrablender configs were set to zero) kept these generation biomes and features intact. i don't know why this behavior is different from 1.18.2, nor understand exactly why this is the case.
3) i had to look carefully for differences when bop terrablender settings were zero vs. default, since in areas terrablender assigns to vanilla, there are many areas where generation is identical (as i manually placed bop biomes where they should be). however, in comparison, if you find areas assigned to bop via terrablender, you can see those only contain bop biomes, even though the cases i saw kept tectonic terrain intact.
4) i definitely had different results when i kept testing without clearing out configs.

So, per this testing, try it this way:
1) delete all configs
2) load minecraft, edit terrablender configs just in bop (ie, in configs/biomesoplenty folder, not general terrablender configs) and zero out the overworld biomes
  > note, if still not working after these steps, repeat from step 1, but after changing configs, quit minecraft and restart in case something is going on that i am missing, e.g. config change not updating without restart
3) i also noticed that i have an additional tectonic-bop pack in datapacks (not built-in) that i don't see in your list, so not sure if you changed anything. either way, i am uploading a new version now to CF that removes the data folder from the main mod, in case that was affecting anything. otherwise, your list ordering above looks good.

Now, I still don't know why you don't have BOP biomes, as no testing steps that I did (apart from excluding the compat, and setting bop terrablender configs to zero) wound up with no BOP biomes. If this is still the case after trying the above, I am stumped, but also have not heard this complaint from anyone else yet, so may be something weird and specific on your end.

**Comment by MysticcWaters** [comment]
So, I initially thought the issue was related to the non-built in tectonic-bop pack, as that pack was in my list, but underneath Default. When I fixed the load order to the below, I got BOP biomes to spawn:

![Datapack Load Order](https://user-images.githubusercontent.com/130418925/231210399-cb4a3c38-b9dc-4e8a-9bba-2fc4509ce013.png)

However, they were spawning in strange locations, and not properly mapped to the terrain. I then tried clearing configs, loading Minecraft, changing the configs, and then restarting before creating the world, and that seemed to fix the issue.

**Comment by djsimmonds** [comment]
thanks. i assume that persistent configs will be the biggest reasons for problems in general with this mod, and clearing out configs will likely solve most issues. i don't think swapping out Tectonic and BOP positioning makes a difference. will close issue.
